/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    UApp: typeof import('./node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+exte_44a045a0e0946ff2a3483f5d9453393f/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UAuthForm: typeof import('./node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+exte_44a045a0e0946ff2a3483f5d9453393f/node_modules/@nuxt/ui/dist/runtime/components/AuthForm.vue')['default']
    UButton: typeof import('./node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+exte_44a045a0e0946ff2a3483f5d9453393f/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCard: typeof import('./node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+exte_44a045a0e0946ff2a3483f5d9453393f/node_modules/@nuxt/ui/dist/runtime/components/Card.vue')['default']
    UDropdownMenu: typeof import('./node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+exte_44a045a0e0946ff2a3483f5d9453393f/node_modules/@nuxt/ui/dist/runtime/components/DropdownMenu.vue')['default']
    UForm: typeof import('./node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+exte_44a045a0e0946ff2a3483f5d9453393f/node_modules/@nuxt/ui/dist/runtime/components/Form.vue')['default']
    UFormField: typeof import('./node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+exte_44a045a0e0946ff2a3483f5d9453393f/node_modules/@nuxt/ui/dist/runtime/components/FormField.vue')['default']
    UHeader: typeof import('./node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+exte_44a045a0e0946ff2a3483f5d9453393f/node_modules/@nuxt/ui/dist/runtime/components/Header.vue')['default']
    UIcon: typeof import('./node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+exte_44a045a0e0946ff2a3483f5d9453393f/node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UInput: typeof import('./node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+exte_44a045a0e0946ff2a3483f5d9453393f/node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UMain: typeof import('./node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+exte_44a045a0e0946ff2a3483f5d9453393f/node_modules/@nuxt/ui/dist/runtime/components/Main.vue')['default']
    UNavigationMenu: typeof import('./node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+exte_44a045a0e0946ff2a3483f5d9453393f/node_modules/@nuxt/ui/dist/runtime/components/NavigationMenu.vue')['default']
    UPageCard: typeof import('./node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+exte_44a045a0e0946ff2a3483f5d9453393f/node_modules/@nuxt/ui/dist/runtime/components/PageCard.vue')['default']
    UPageHero: typeof import('./node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+exte_44a045a0e0946ff2a3483f5d9453393f/node_modules/@nuxt/ui/dist/runtime/components/PageHero.vue')['default']
    USidebar: typeof import('./node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+exte_44a045a0e0946ff2a3483f5d9453393f/node_modules/@nuxt/ui/dist/runtime/components/Sidebar.vue')['default']
    UTable: typeof import('./node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+exte_44a045a0e0946ff2a3483f5d9453393f/node_modules/@nuxt/ui/dist/runtime/components/Table.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
